server:
  port: 9999

spring:
  application:
    name: mq-server
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 50
      idle-timeout: 30

  jms:
    pub-sub-domain: true